// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: gt_common.proto
package com.gt.sdk.base.models;

import android.os.Parcelable;

import com.czhj.wire.AndroidMessage;
import com.czhj.wire.FieldEncoding;
import com.czhj.wire.Message;
import com.czhj.wire.ProtoAdapter;
import com.czhj.wire.ProtoReader;
import com.czhj.wire.ProtoWriter;
import com.czhj.wire.WireField;
import com.czhj.wire.internal.Internal;
import com.czhj.wire.okio.ByteString;

import java.io.IOException;
import java.util.List;

public final class App extends AndroidMessage<App, App.Builder> {

    public static final ProtoAdapter<App> ADAPTER = new ProtoAdapter_App();

    public static final Parcelable.Creator<App> CREATOR = AndroidMessage.newCreator(ADAPTER);

    private static final long serialVersionUID = 0L;

    public static final String DEFAULT_ID = "";

    public static final String DEFAULT_NAME = "";

    public static final String DEFAULT_VER = "";

    public static final String DEFAULT_BUNDLE = "";

    public static final String DEFAULT_STORE_VER = "";

    /**
     * 应用标识
     */
    @WireField(tag = 1, adapter = "com.squareup.wire.ProtoAdapter#STRING")
    public final String id;

    /**
     * 应⽤名称
     */
    @WireField(tag = 2, adapter = "com.squareup.wire.ProtoAdapter#STRING")
    public final String name;

    /**
     * 应⽤版本
     */
    @WireField(tag = 3, adapter = "com.squareup.wire.ProtoAdapter#STRING")
    public final String ver;

    /**
     * 必填！应用包名。IOS设备为bundle id
     */
    @WireField(tag = 4, adapter = "com.squareup.wire.ProtoAdapter#STRING")
    public final String bundle;

    /**
     * app 所属类别
     */
    @WireField(tag = 5, adapter = "com.squareup.wire.ProtoAdapter#STRING", label = WireField.Label.REPEATED)
    public final List<String> cat;

    /**
     * app当前页面的分类信息标签列表
     */
    @WireField(tag = 6, adapter = "com.squareup.wire.ProtoAdapter#STRING", label = WireField.Label.REPEATED)
    public final List<String> pagecat;

    /**
     * app 关键字标签列表
     */
    @WireField(tag = 7, adapter = "com.squareup.wire.ProtoAdapter#STRING", label = WireField.Label.REPEATED)
    public final List<String> keywords;

    /**
     * App的应用商店版本
     */
    @WireField(tag = 8, adapter = "com.squareup.wire.ProtoAdapter#STRING")
    public final String store_ver;

    public App(String id, String name, String ver, String bundle, List<String> cat, List<String> pagecat, List<String> keywords, String store_ver) {
        this(id, name, ver, bundle, cat, pagecat, keywords, store_ver, ByteString.EMPTY);
    }

    public App(String id, String name, String ver, String bundle, List<String> cat, List<String> pagecat, List<String> keywords, String store_ver, ByteString unknownFields) {
        super(ADAPTER, unknownFields);
        this.id = id;
        this.name = name;
        this.ver = ver;
        this.bundle = bundle;
        this.cat = Internal.immutableCopyOf("cat", cat);
        this.pagecat = Internal.immutableCopyOf("pagecat", pagecat);
        this.keywords = Internal.immutableCopyOf("keywords", keywords);
        this.store_ver = store_ver;
    }

    @Override
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.name = name;
        builder.ver = ver;
        builder.bundle = bundle;
        builder.cat = Internal.copyOf("cat", cat);
        builder.pagecat = Internal.copyOf("pagecat", pagecat);
        builder.keywords = Internal.copyOf("keywords", keywords);
        builder.store_ver = store_ver;
        builder.addUnknownFields(unknownFields());
        return builder;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof App)) return false;
        App o = (App) other;
        return unknownFields().equals(o.unknownFields()) && Internal.equals(id, o.id) && Internal.equals(name, o.name) && Internal.equals(ver, o.ver) && Internal.equals(bundle, o.bundle) && cat.equals(o.cat) && pagecat.equals(o.pagecat) && keywords.equals(o.keywords) && Internal.equals(store_ver, o.store_ver);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode;
        if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + (id != null ? id.hashCode() : 0);
            result = result * 37 + (name != null ? name.hashCode() : 0);
            result = result * 37 + (ver != null ? ver.hashCode() : 0);
            result = result * 37 + (bundle != null ? bundle.hashCode() : 0);
            result = result * 37 + cat.hashCode();
            result = result * 37 + pagecat.hashCode();
            result = result * 37 + keywords.hashCode();
            result = result * 37 + (store_ver != null ? store_ver.hashCode() : 0);
            super.hashCode = result;
        }
        return result;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        if (id != null) builder.append(", id=").append(id);
        if (name != null) builder.append(", name=").append(name);
        if (ver != null) builder.append(", ver=").append(ver);
        if (bundle != null) builder.append(", bundle=").append(bundle);
        if (!cat.isEmpty()) builder.append(", cat=").append(cat);
        if (!pagecat.isEmpty()) builder.append(", pagecat=").append(pagecat);
        if (!keywords.isEmpty()) builder.append(", keywords=").append(keywords);
        if (store_ver != null) builder.append(", store_ver=").append(store_ver);
        return builder.replace(0, 2, "App{").append('}').toString();
    }

    public static final class Builder extends Message.Builder<App, Builder> {
        public String id = DEFAULT_ID;

        public String name = DEFAULT_NAME;

        public String ver = DEFAULT_VER;

        public String bundle = DEFAULT_BUNDLE;

        public List<String> cat;

        public List<String> pagecat;

        public List<String> keywords;

        public String store_ver = DEFAULT_STORE_VER;

        public Builder() {
            cat = Internal.newMutableList();
            pagecat = Internal.newMutableList();
            keywords = Internal.newMutableList();
        }

        /**
         * 应用标识
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * 应⽤名称
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * 应⽤版本
         */
        public Builder ver(String ver) {
            this.ver = ver;
            return this;
        }

        /**
         * 必填！应用包名。IOS设备为bundle id
         */
        public Builder bundle(String bundle) {
            this.bundle = bundle;
            return this;
        }

        /**
         * app 所属类别
         */
        public Builder cat(List<String> cat) {
            Internal.checkElementsNotNull(cat);
            this.cat = cat;
            return this;
        }

        /**
         * app当前页面的分类信息标签列表
         */
        public Builder pagecat(List<String> pagecat) {
            Internal.checkElementsNotNull(pagecat);
            this.pagecat = pagecat;
            return this;
        }

        /**
         * app 关键字标签列表
         */
        public Builder keywords(List<String> keywords) {
            Internal.checkElementsNotNull(keywords);
            this.keywords = keywords;
            return this;
        }

        /**
         * App的应用商店版本
         */
        public Builder store_ver(String store_ver) {
            this.store_ver = store_ver;
            return this;
        }

        @Override
        public App build() {
            return new App(id, name, ver, bundle, cat, pagecat, keywords, store_ver, super.buildUnknownFields());
        }
    }

    private static final class ProtoAdapter_App extends ProtoAdapter<App> {
        public ProtoAdapter_App() {
            super(FieldEncoding.LENGTH_DELIMITED, App.class);
        }

        @Override
        public int encodedSize(App value) {
            return ProtoAdapter.STRING.encodedSizeWithTag(1, value.id) + ProtoAdapter.STRING.encodedSizeWithTag(2, value.name) + ProtoAdapter.STRING.encodedSizeWithTag(3, value.ver) + ProtoAdapter.STRING.encodedSizeWithTag(4, value.bundle) + ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(5, value.cat) + ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(6, value.pagecat) + ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(7, value.keywords) + ProtoAdapter.STRING.encodedSizeWithTag(8, value.store_ver) + value.unknownFields().size();
        }

        @Override
        public void encode(ProtoWriter writer, App value) throws IOException {
            ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id);
            ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name);
            ProtoAdapter.STRING.encodeWithTag(writer, 3, value.ver);
            ProtoAdapter.STRING.encodeWithTag(writer, 4, value.bundle);
            ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 5, value.cat);
            ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 6, value.pagecat);
            ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 7, value.keywords);
            ProtoAdapter.STRING.encodeWithTag(writer, 8, value.store_ver);
            writer.writeBytes(value.unknownFields());
        }

        @Override
        public App decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1; ) {
                switch (tag) {
                    case 1:
                        builder.id(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 2:
                        builder.name(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 3:
                        builder.ver(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 4:
                        builder.bundle(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 5:
                        builder.cat.add(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 6:
                        builder.pagecat.add(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 7:
                        builder.keywords.add(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 8:
                        builder.store_ver(ProtoAdapter.STRING.decode(reader));
                        break;
                    default: {
                        FieldEncoding fieldEncoding = reader.peekFieldEncoding();
                        Object value = fieldEncoding.rawProtoAdapter().decode(reader);
                        builder.addUnknownField(tag, fieldEncoding, value);
                    }
                }
            }
            reader.endMessage(token);
            return builder.build();
        }

        @Override
        public App redact(App value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
        }
    }
}
