// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: sigmob_ssp_config.proto
package com.sigmob.sdk.base.models.config;

import android.os.Parcelable;

import com.czhj.wire.AndroidMessage;
import com.czhj.wire.FieldEncoding;
import com.czhj.wire.Message;
import com.czhj.wire.ProtoAdapter;
import com.czhj.wire.ProtoReader;
import com.czhj.wire.ProtoWriter;
import com.czhj.wire.WireField;
import com.czhj.wire.internal.Internal;
import com.czhj.wire.okio.ByteString;

import java.io.IOException;

/**
 * 通用地址配置
 */
public final class SigmobCommonEndpointsConfig extends AndroidMessage<SigmobCommonEndpointsConfig, SigmobCommonEndpointsConfig.Builder> {
  public static final ProtoAdapter<SigmobCommonEndpointsConfig> ADAPTER = new ProtoAdapter_SigmobCommonEndpointsConfig();

  public static final Parcelable.Creator<SigmobCommonEndpointsConfig> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_LOG = "";

  public static final String DEFAULT_ADS = "";

  public static final String DEFAULT_HB_ADS = "";

  public static final String DEFAULT_FEEDBACK = "";

  public static final String DEFAULT_CONFIG = "";

  public static final String DEFAULT_NATIVE_AD = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String log;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String ads;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String hb_ads;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String feedback;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String config;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String native_ad;

  public SigmobCommonEndpointsConfig(String log, String ads, String hb_ads, String feedback,
      String config, String native_ad) {
    this(log, ads, hb_ads, feedback, config, native_ad, ByteString.EMPTY);
  }

  public SigmobCommonEndpointsConfig(String log, String ads, String hb_ads, String feedback,
      String config, String native_ad, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.log = log;
    this.ads = ads;
    this.hb_ads = hb_ads;
    this.feedback = feedback;
    this.config = config;
    this.native_ad = native_ad;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.log = log;
    builder.ads = ads;
    builder.hb_ads = hb_ads;
    builder.feedback = feedback;
    builder.config = config;
    builder.native_ad = native_ad;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SigmobCommonEndpointsConfig)) return false;
    SigmobCommonEndpointsConfig o = (SigmobCommonEndpointsConfig) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(log, o.log)
        && Internal.equals(ads, o.ads)
        && Internal.equals(hb_ads, o.hb_ads)
        && Internal.equals(feedback, o.feedback)
        && Internal.equals(config, o.config)
        && Internal.equals(native_ad, o.native_ad);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (log != null ? log.hashCode() : 0);
      result = result * 37 + (ads != null ? ads.hashCode() : 0);
      result = result * 37 + (hb_ads != null ? hb_ads.hashCode() : 0);
      result = result * 37 + (feedback != null ? feedback.hashCode() : 0);
      result = result * 37 + (config != null ? config.hashCode() : 0);
      result = result * 37 + (native_ad != null ? native_ad.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (log != null) builder.append(", log=").append(log);
    if (ads != null) builder.append(", ads=").append(ads);
    if (hb_ads != null) builder.append(", hb_ads=").append(hb_ads);
    if (feedback != null) builder.append(", feedback=").append(feedback);
    if (config != null) builder.append(", config=").append(config);
    if (native_ad != null) builder.append(", native_ad=").append(native_ad);
    return builder.replace(0, 2, "SigmobCommonEndpointsConfig{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SigmobCommonEndpointsConfig, Builder> {
    public String log;

    public String ads;

    public String hb_ads;

    public String feedback;

    public String config;

    public String native_ad;

    public Builder() {
    }

    public Builder log(String log) {
      this.log = log;
      return this;
    }

    public Builder ads(String ads) {
      this.ads = ads;
      return this;
    }

    public Builder hb_ads(String hb_ads) {
      this.hb_ads = hb_ads;
      return this;
    }

    public Builder feedback(String feedback) {
      this.feedback = feedback;
      return this;
    }

    public Builder config(String config) {
      this.config = config;
      return this;
    }

    public Builder native_ad(String native_ad) {
      this.native_ad = native_ad;
      return this;
    }

    @Override
    public SigmobCommonEndpointsConfig build() {
      return new SigmobCommonEndpointsConfig(log, ads, hb_ads, feedback, config, native_ad, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SigmobCommonEndpointsConfig extends ProtoAdapter<SigmobCommonEndpointsConfig> {
    public ProtoAdapter_SigmobCommonEndpointsConfig() {
      super(FieldEncoding.LENGTH_DELIMITED, SigmobCommonEndpointsConfig.class);
    }

    @Override
    public int encodedSize(SigmobCommonEndpointsConfig value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.log)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.ads)
          + ProtoAdapter.STRING.encodedSizeWithTag(3, value.hb_ads)
          + ProtoAdapter.STRING.encodedSizeWithTag(4, value.feedback)
          + ProtoAdapter.STRING.encodedSizeWithTag(5, value.config)
          + ProtoAdapter.STRING.encodedSizeWithTag(6, value.native_ad)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, SigmobCommonEndpointsConfig value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.log);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.ads);
      ProtoAdapter.STRING.encodeWithTag(writer, 3, value.hb_ads);
      ProtoAdapter.STRING.encodeWithTag(writer, 4, value.feedback);
      ProtoAdapter.STRING.encodeWithTag(writer, 5, value.config);
      ProtoAdapter.STRING.encodeWithTag(writer, 6, value.native_ad);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public SigmobCommonEndpointsConfig decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.log(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.ads(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.hb_ads(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.feedback(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.config(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.native_ad(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public SigmobCommonEndpointsConfig redact(SigmobCommonEndpointsConfig value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
