// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: sigmob_ssp_response.proto
package com.sigmob.sdk.base.models.rtb;

import android.os.Parcelable;

import com.czhj.wire.AndroidMessage;
import com.czhj.wire.FieldEncoding;
import com.czhj.wire.Message;
import com.czhj.wire.ProtoAdapter;
import com.czhj.wire.ProtoReader;
import com.czhj.wire.ProtoWriter;
import com.czhj.wire.WireField;
import com.czhj.wire.internal.Internal;
import com.czhj.wire.okio.ByteString;

import java.io.IOException;

public final class ResponseAssetVideo extends AndroidMessage<ResponseAssetVideo, ResponseAssetVideo.Builder> {
    public static final ProtoAdapter<ResponseAssetVideo> ADAPTER = new ProtoAdapter_ResponseAssetVideo();

    public static final Parcelable.Creator<ResponseAssetVideo> CREATOR = AndroidMessage.newCreator(ADAPTER);

    private static final long serialVersionUID = 0L;

    public static final String DEFAULT_URL = "";

    public static final Integer DEFAULT_W = 0;

    public static final Integer DEFAULT_H = 0;

    public static final Integer DEFAULT_DURATION = 0;

    /**
     * 视频url
     */
    @WireField(
            tag = 1,
            adapter = "com.squareup.wire.ProtoAdapter#STRING"
    )
    public final String url;

    /**
     * 视频素材宽度，原生广告，该字段必填
     */
    @WireField(
            tag = 2,
            adapter = "com.squareup.wire.ProtoAdapter#UINT32"
    )
    public final Integer w;

    /**
     * 视频素材高度，原生广告，该字段必填
     */
    @WireField(
            tag = 3,
            adapter = "com.squareup.wire.ProtoAdapter#UINT32"
    )
    public final Integer h;

    /**
     * 视频时长
     */
    @WireField(
            tag = 4,
            adapter = "com.squareup.wire.ProtoAdapter#UINT32"
    )
    public final Integer duration;

    public ResponseAssetVideo(String url, Integer w, Integer h, Integer duration) {
        this(url, w, h, duration, ByteString.EMPTY);
    }

    public ResponseAssetVideo(String url, Integer w, Integer h, Integer duration,
                              ByteString unknownFields) {
        super(ADAPTER, unknownFields);
        this.url = url;
        this.w = w;
        this.h = h;
        this.duration = duration;
    }

    @Override
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.url = url;
        builder.w = w;
        builder.h = h;
        builder.duration = duration;
        builder.addUnknownFields(unknownFields());
        return builder;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof ResponseAssetVideo)) return false;
        ResponseAssetVideo o = (ResponseAssetVideo) other;
        return unknownFields().equals(o.unknownFields())
                && Internal.equals(url, o.url)
                && Internal.equals(w, o.w)
                && Internal.equals(h, o.h)
                && Internal.equals(duration, o.duration);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode;
        if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + (url != null ? url.hashCode() : 0);
            result = result * 37 + (w != null ? w.hashCode() : 0);
            result = result * 37 + (h != null ? h.hashCode() : 0);
            result = result * 37 + (duration != null ? duration.hashCode() : 0);
            super.hashCode = result;
        }
        return result;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        if (url != null) builder.append(", url=").append(url);
        if (w != null) builder.append(", w=").append(w);
        if (h != null) builder.append(", h=").append(h);
        if (duration != null) builder.append(", duration=").append(duration);
        return builder.replace(0, 2, "ResponseAssetVideo{").append('}').toString();
    }

    public static final class Builder extends Message.Builder<ResponseAssetVideo, Builder> {
        public String url = DEFAULT_URL;

        public Integer w = DEFAULT_W;

        public Integer h = DEFAULT_H;

        public Integer duration = DEFAULT_DURATION;

        public Builder() {
        }

        /**
         * 视频url
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * 视频素材宽度，原生广告，该字段必填
         */
        public Builder w(Integer w) {
            this.w = w;
            return this;
        }

        /**
         * 视频素材高度，原生广告，该字段必填
         */
        public Builder h(Integer h) {
            this.h = h;
            return this;
        }

        /**
         * 视频时长
         */
        public Builder duration(Integer duration) {
            this.duration = duration;
            return this;
        }

        @Override
        public ResponseAssetVideo build() {
            return new ResponseAssetVideo(url, w, h, duration, super.buildUnknownFields());
        }
    }

    private static final class ProtoAdapter_ResponseAssetVideo extends ProtoAdapter<ResponseAssetVideo> {
        public ProtoAdapter_ResponseAssetVideo() {
            super(FieldEncoding.LENGTH_DELIMITED, ResponseAssetVideo.class);
        }

        @Override
        public int encodedSize(ResponseAssetVideo value) {
            return ProtoAdapter.STRING.encodedSizeWithTag(1, value.url)
                    + ProtoAdapter.UINT32.encodedSizeWithTag(2, value.w)
                    + ProtoAdapter.UINT32.encodedSizeWithTag(3, value.h)
                    + ProtoAdapter.UINT32.encodedSizeWithTag(4, value.duration)
                    + value.unknownFields().size();
        }

        @Override
        public void encode(ProtoWriter writer, ResponseAssetVideo value) throws IOException {
            ProtoAdapter.STRING.encodeWithTag(writer, 1, value.url);
            ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.w);
            ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.h);
            ProtoAdapter.UINT32.encodeWithTag(writer, 4, value.duration);
            writer.writeBytes(value.unknownFields());
        }

        @Override
        public ResponseAssetVideo decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1; ) {
                switch (tag) {
                    case 1:
                        builder.url(ProtoAdapter.STRING.decode(reader));
                        break;
                    case 2:
                        builder.w(ProtoAdapter.UINT32.decode(reader));
                        break;
                    case 3:
                        builder.h(ProtoAdapter.UINT32.decode(reader));
                        break;
                    case 4:
                        builder.duration(ProtoAdapter.UINT32.decode(reader));
                        break;
                    default: {
                        FieldEncoding fieldEncoding = reader.peekFieldEncoding();
                        Object value = fieldEncoding.rawProtoAdapter().decode(reader);
                        builder.addUnknownField(tag, fieldEncoding, value);
                    }
                }
            }
            reader.endMessage(token);
            return builder.build();
        }

        @Override
        public ResponseAssetVideo redact(ResponseAssetVideo value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
        }
    }
}
