// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: sigmob_ssp_response.proto
package com.sigmob.sdk.base.models.rtb;

import android.os.Parcelable;

import com.czhj.wire.AndroidMessage;
import com.czhj.wire.FieldEncoding;
import com.czhj.wire.Message;
import com.czhj.wire.ProtoAdapter;
import com.czhj.wire.ProtoReader;
import com.czhj.wire.ProtoWriter;
import com.czhj.wire.WireField;
import com.czhj.wire.internal.Internal;
import com.czhj.wire.okio.ByteString;

import java.io.IOException;


public final class Widget extends AndroidMessage<Widget, Widget.Builder> {
    public static final ProtoAdapter<Widget> ADAPTER = new ProtoAdapter_Widget();

    public static final Parcelable.Creator<Widget> CREATOR = AndroidMessage.newCreator(ADAPTER);

    private static final long serialVersionUID = 0L;

    public static final Long DEFAULT_WIDGET_ID = 0L;

    /**
     * 挂件id
     */
    @WireField(
            tag = 1,
            adapter = "com.squareup.wire.ProtoAdapter#UINT64"
    )
    public final Long widget_id;

    public Widget(Long widget_id) {
        this(widget_id, ByteString.EMPTY);
    }

    public Widget(Long widget_id, ByteString unknownFields) {
        super(ADAPTER, unknownFields);
        this.widget_id = widget_id;
    }

    @Override
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.widget_id = widget_id;
        builder.addUnknownFields(unknownFields());
        return builder;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof Widget)) return false;
        Widget o = (Widget) other;
        return unknownFields().equals(o.unknownFields())
                && Internal.equals(widget_id, o.widget_id);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode;
        if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + (widget_id != null ? widget_id.hashCode() : 0);
            super.hashCode = result;
        }
        return result;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        if (widget_id != null) builder.append(", widget_id=").append(widget_id);
        return builder.replace(0, 2, "Widget{").append('}').toString();
    }

    public static final class Builder extends Message.Builder<Widget, Builder> {
        public Long widget_id = DEFAULT_WIDGET_ID;

        public Builder() {
        }

        /**
         * 挂件id
         */
        public Builder widget_id(Long widget_id) {
            this.widget_id = widget_id;
            return this;
        }

        @Override
        public Widget build() {
            return new Widget(widget_id, super.buildUnknownFields());
        }
    }

    private static final class ProtoAdapter_Widget extends ProtoAdapter<Widget> {
        public ProtoAdapter_Widget() {
            super(FieldEncoding.LENGTH_DELIMITED, Widget.class);
        }

        @Override
        public int encodedSize(Widget value) {
            return ProtoAdapter.UINT64.encodedSizeWithTag(1, value.widget_id)
                    + value.unknownFields().size();
        }

        @Override
        public void encode(ProtoWriter writer, Widget value) throws IOException {
            ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.widget_id);
            writer.writeBytes(value.unknownFields());
        }

        @Override
        public Widget decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1; ) {
                switch (tag) {
                    case 1:
                        builder.widget_id(ProtoAdapter.UINT64.decode(reader));
                        break;
                    default: {
                        FieldEncoding fieldEncoding = reader.peekFieldEncoding();
                        Object value = fieldEncoding.rawProtoAdapter().decode(reader);
                        builder.addUnknownField(tag, fieldEncoding, value);
                    }
                }
            }
            reader.endMessage(token);
            return builder.build();
        }

        @Override
        public Widget redact(Widget value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
        }
    }
}
