// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: gt_common.proto
package com.gt.sdk.base.models.rtb;

import android.os.Parcelable;

import com.czhj.wire.AndroidMessage;
import com.czhj.wire.FieldEncoding;
import com.czhj.wire.Message;
import com.czhj.wire.ProtoAdapter;
import com.czhj.wire.ProtoReader;
import com.czhj.wire.ProtoWriter;
import com.czhj.wire.WireField;
import com.czhj.wire.internal.Internal;
import com.czhj.wire.okio.ByteString;

import java.io.IOException;

public final class Geo extends AndroidMessage<Geo, Geo.Builder> {
    public static final ProtoAdapter<Geo> ADAPTER = new ProtoAdapter_Geo();

    public static final Parcelable.Creator<Geo> CREATOR = AndroidMessage.newCreator(ADAPTER);

    private static final long serialVersionUID = 0L;

    public static final Float DEFAULT_LAT = 0.0f;

    public static final Float DEFAULT_LON = 0.0f;

    /**
     * 纬度
     */
    @WireField(tag = 1, adapter = "com.squareup.wire.ProtoAdapter#FLOAT")
    public final Float lat;

    /**
     * 经度
     */
    @WireField(tag = 2, adapter = "com.squareup.wire.ProtoAdapter#FLOAT")
    public final Float lon;

    public Geo(Float lat, Float lon) {
        this(lat, lon, ByteString.EMPTY);
    }

    public Geo(Float lat, Float lon, ByteString unknownFields) {
        super(ADAPTER, unknownFields);
        this.lat = lat;
        this.lon = lon;
    }

    @Override
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.lat = lat;
        builder.lon = lon;
        builder.addUnknownFields(unknownFields());
        return builder;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof Geo)) return false;
        Geo o = (Geo) other;
        return unknownFields().equals(o.unknownFields()) && Internal.equals(lat, o.lat) && Internal.equals(lon, o.lon);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode;
        if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + (lat != null ? lat.hashCode() : 0);
            result = result * 37 + (lon != null ? lon.hashCode() : 0);
            super.hashCode = result;
        }
        return result;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        if (lat != null) builder.append(", lat=").append(lat);
        if (lon != null) builder.append(", lon=").append(lon);
        return builder.replace(0, 2, "Geo{").append('}').toString();
    }

    public static final class Builder extends Message.Builder<Geo, Builder> {
        public Float lat = DEFAULT_LAT;

        public Float lon = DEFAULT_LON;

        public Builder() {
        }

        /**
         * 纬度
         */
        public Builder lat(Float lat) {
            this.lat = lat;
            return this;
        }

        /**
         * 经度
         */
        public Builder lon(Float lon) {
            this.lon = lon;
            return this;
        }

        @Override
        public Geo build() {
            return new Geo(lat, lon, super.buildUnknownFields());
        }
    }

    private static final class ProtoAdapter_Geo extends ProtoAdapter<Geo> {
        public ProtoAdapter_Geo() {
            super(FieldEncoding.LENGTH_DELIMITED, Geo.class);
        }

        @Override
        public int encodedSize(Geo value) {
            return ProtoAdapter.FLOAT.encodedSizeWithTag(1, value.lat) + ProtoAdapter.FLOAT.encodedSizeWithTag(2, value.lon) + value.unknownFields().size();
        }

        @Override
        public void encode(ProtoWriter writer, Geo value) throws IOException {
            ProtoAdapter.FLOAT.encodeWithTag(writer, 1, value.lat);
            ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.lon);
            writer.writeBytes(value.unknownFields());
        }

        @Override
        public Geo decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1; ) {
                switch (tag) {
                    case 1:
                        builder.lat(ProtoAdapter.FLOAT.decode(reader));
                        break;
                    case 2:
                        builder.lon(ProtoAdapter.FLOAT.decode(reader));
                        break;
                    default: {
                        FieldEncoding fieldEncoding = reader.peekFieldEncoding();
                        Object value = fieldEncoding.rawProtoAdapter().decode(reader);
                        builder.addUnknownField(tag, fieldEncoding, value);
                    }
                }
            }
            reader.endMessage(token);
            return builder.build();
        }

        @Override
        public Geo redact(Geo value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
        }
    }
}
