// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: gt_ssp_config.proto
package com.gt.sdk.base.models.config;

import android.os.Parcelable;

import com.czhj.wire.AndroidMessage;
import com.czhj.wire.FieldEncoding;
import com.czhj.wire.Message;
import com.czhj.wire.ProtoAdapter;
import com.czhj.wire.ProtoReader;
import com.czhj.wire.ProtoWriter;
import com.czhj.wire.WireField;
import com.czhj.wire.internal.Internal;
import com.czhj.wire.okio.ByteString;

import java.io.IOException;


public final class NativeConfig extends AndroidMessage<NativeConfig, NativeConfig.Builder> {

    public static final ProtoAdapter<NativeConfig> ADAPTER = new ProtoAdapter_NativeConfig();

    public static final Parcelable.Creator<NativeConfig> CREATOR = AndroidMessage.newCreator(ADAPTER);

    private static final long serialVersionUID = 0L;

    public static final Integer DEFAULT_CACHETOP = 0;

    public static final Integer DEFAULT_AD_LOAD_TIMEOUT = 0;

    /**
     * 原生广告素材缓存上限，小于等于0，则清除缓存
     */
    @WireField(tag = 1, adapter = "com.squareup.wire.ProtoAdapter#INT32")
    public final Integer cacheTop;

    /**
     * 广告总超时
     */
    @WireField(tag = 2, adapter = "com.squareup.wire.ProtoAdapter#UINT32")
    public final Integer ad_load_timeout;

    public NativeConfig(Integer cacheTop, Integer ad_load_timeout) {
        this(cacheTop, ad_load_timeout, ByteString.EMPTY);
    }

    public NativeConfig(Integer cacheTop, Integer ad_load_timeout, ByteString unknownFields) {
        super(ADAPTER, unknownFields);
        this.cacheTop = cacheTop;
        this.ad_load_timeout = ad_load_timeout;
    }

    @Override
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.cacheTop = cacheTop;
        builder.ad_load_timeout = ad_load_timeout;
        builder.addUnknownFields(unknownFields());
        return builder;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof NativeConfig)) return false;
        NativeConfig o = (NativeConfig) other;
        return unknownFields().equals(o.unknownFields()) && Internal.equals(cacheTop, o.cacheTop) && Internal.equals(ad_load_timeout, o.ad_load_timeout);
    }

    @Override
    public int hashCode() {
        int result = super.hashCode;
        if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + (cacheTop != null ? cacheTop.hashCode() : 0);
            result = result * 37 + (ad_load_timeout != null ? ad_load_timeout.hashCode() : 0);
            super.hashCode = result;
        }
        return result;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        if (cacheTop != null) builder.append(", cacheTop=").append(cacheTop);
        if (ad_load_timeout != null) builder.append(", ad_load_timeout=").append(ad_load_timeout);
        return builder.replace(0, 2, "NativeConfig{").append('}').toString();
    }

    public static final class Builder extends Message.Builder<NativeConfig, Builder> {
        public Integer cacheTop = DEFAULT_CACHETOP;

        public Integer ad_load_timeout = DEFAULT_AD_LOAD_TIMEOUT;

        public Builder() {
        }

        /**
         * 原生广告素材缓存上限，小于等于0，则清除缓存
         */
        public Builder cacheTop(Integer cacheTop) {
            this.cacheTop = cacheTop;
            return this;
        }

        /**
         * 广告总超时
         */
        public Builder ad_load_timeout(Integer ad_load_timeout) {
            this.ad_load_timeout = ad_load_timeout;
            return this;
        }

        @Override
        public NativeConfig build() {
            return new NativeConfig(cacheTop, ad_load_timeout, super.buildUnknownFields());
        }
    }

    private static final class ProtoAdapter_NativeConfig extends ProtoAdapter<NativeConfig> {
        public ProtoAdapter_NativeConfig() {
            super(FieldEncoding.LENGTH_DELIMITED, NativeConfig.class);
        }

        @Override
        public int encodedSize(NativeConfig value) {
            return ProtoAdapter.INT32.encodedSizeWithTag(1, value.cacheTop) + ProtoAdapter.UINT32.encodedSizeWithTag(2, value.ad_load_timeout) + value.unknownFields().size();
        }

        @Override
        public void encode(ProtoWriter writer, NativeConfig value) throws IOException {
            ProtoAdapter.INT32.encodeWithTag(writer, 1, value.cacheTop);
            ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.ad_load_timeout);
            writer.writeBytes(value.unknownFields());
        }

        @Override
        public NativeConfig decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1; ) {
                switch (tag) {
                    case 1:
                        builder.cacheTop(ProtoAdapter.INT32.decode(reader));
                        break;
                    case 2:
                        builder.ad_load_timeout(ProtoAdapter.UINT32.decode(reader));
                        break;
                    default: {
                        FieldEncoding fieldEncoding = reader.peekFieldEncoding();
                        Object value = fieldEncoding.rawProtoAdapter().decode(reader);
                        builder.addUnknownField(tag, fieldEncoding, value);
                    }
                }
            }
            reader.endMessage(token);
            return builder.build();
        }

        @Override
        public NativeConfig redact(NativeConfig value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
        }
    }
}
